version: '3'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecamazon_users
